Repository PerlDancer/Dancer2, pull requests merged in 2021-06, with the labels that each got.

#1623 Copy Dockerfile from the right spot
  lib/Dancer2/CLI/Gen.pm
Labels: Blocked, Bug

#1625 Fix missing gen subcommand in tutorial (#1624)
  lib/Dancer2/Tutorial.pod
Labels: Bug, Documentation

#1626 Add File::Which to Dancer2 dependencies
  cpanfile
Labels: Bug
